# Notebook Pipeline geospatial

## Charge Openstreetmap data:

with the following script, the data from Openstretmap is uploaded and saved in a json format.

```
# the objective of this script is to extract OpenStreetMap data using the Overpass API and a specific bounding box query. The script sends a POST request to the Overpass API with a defined query, retrieves the data in JSON format, and prints the result in a readable format.
import json
import os
import time
import requests

# Define the Overpass API endpoint URL for querying OpenStreetMap data.
url = "https://overpass-api.de/api/interpreter"

# Define the Overpass QL query to retrieve ways within a specific bounding box.
# Bounding box coordinates: (south, west, north, east) correspond to the area of interest.
# Coordinates are in the format: (latitude, longitude)
# south is the minimum latitude, west is the minimum longitude, north is the maximum latitude, and east is the maximum longitude.
# out:json specifies that the output format should be JSON.
# timeout:90 sets the maximum time (in seconds) that the query is allowed to run before timing out.
# way(...) specifies the way elements to retrieve, with the coordinates defining the area of interest.
# way(30.626917110746, -96.348809105664, 30.634468750236, -96.339893442898) defines a specific way to retrieve based on its coordinates.
# out geom specifies that the output should include the geometry of the ways.
query = """
  [bbox:30.618338,-96.323712,30.591028,-96.330826] 
  [out:json]
  [timeout:90]
  ;
  way(30.626917110746, -96.348809105664, 30.634468750236, -96.339893442898);
  out geom;
"""
# Send a POST request to the Overpass API with the defined query and appropriate headers.
# data={"data": query} sends the query as form data in the request body.
# headers={"Accept": "application/json", "User-Agent": "geospatial-project/1.0"} sets the request headers to specify that the client expects a JSON response and identifies the user agent.
# timeout=120 sets the maximum time (in seconds) that the request is allowed to take before timing out.
response = requests.post(
    url,
    data={"data": query},
  headers={
    "Accept": "application/json",
    "User-Agent": "geospatial-project/1.0",
  },
    timeout=120,
)
# Check if the request was successful (status code 200). If not, raise an HTTPError exception.
response.raise_for_status()
# Parse the JSON response from the Overpass API and store it in the variable 'result'.
result = response.json()

# Print the retrieved OpenStreetMap data in a readable JSON format with an indentation of 2 spaces.
# indent=2 makes the output more human-readable by adding line breaks and indentation.
print(json.dumps(result, indent=2))
temps = time.strftime("%Y-%m-%d_%H-%M-%S", time.localtime())

# Save the retrieved data to a JSON file named "extracted_data_<timestamp>.json" in the current working directory.
with open(f"extracted_data_{temps}.json", "w", encoding="utf-8") as f:
    json.dump(result, f, ensure_ascii=False, indent=2)
print(f"Data saved to extracted_data_{temps}.json")
print(os.path.abspath(f"extracted_data_{temps}.json"))
```

The file is placed on GitHub in order to use Airbyte to extract it in PostgreSQL.

# Airbyte 

Create the destination in Airbyte with the following information for example:

```
Postgres-local-geospatial
Postgres v3.0.16

Settings

Connections


Destination Settings
Destination name
Postgres-local-geospatial
Connection
Host
host.docker.internal
Port
5432
Database Name
pipeline_geospatial
Default Schema
raw
Username
postgres
SSL Modes

disable
SSH Tunnel Method

No Tunnel

Optional fields

Password
Optional

••••••••••

Edit

SSL Connection
JDBC URL Params
Optional

Airbyte Internal Schema Name
Optional


Disable Final Tables. (WARNING! Unstable option; Columns in raw table schema might change between versions)

Drop tables with CASCADE. (WARNING! Risk of unrecoverable data loss)

Unconstrained numeric columns
Sync Behavior
CDC deletion mode
Optional


Hard delete

```

Create the source, for example:

```
Create a source

File (CSV, JSON, Excel, Feather, Parquet)

Source name
extracted_geo_data
Dataset Name
extracted_geo_data
Required

File Format

json
Storage Provider

HTTPS: Public Web

Optional fields

URL
https://raw.githubusercontent.com/Sebules/pipeline_geospatial/refs/heads/main/extracted_data_bbox_example.json
Required


Optional fields

Reader Options
Optional

```
And then, create the connection between the source and the destination. After synchronization, the data is charged in PostgreSQL.

In [1]:
import pandas as pd
import geopandas as gpd
import numpy as np
import os
import folium
from branca.colormap import LinearColormap
from pathlib import Path
from sqlalchemy import create_engine, text
from geoalchemy2 import Geometry
from dotenv import load_dotenv
from urllib.parse import quote_plus

In [2]:
load_dotenv()  # Load environment variables from .env file

True

In [3]:
# PostgreSQL password
env_pass = os.getenv("PASSWORD")
password = quote_plus(env_pass)

# Connexion to local PostgreSQL 
engine = create_engine(f'postgresql://postgres:{password}@localhost:5432/pipeline_geospatial')

In [7]:
# Check database contents
with engine.connect() as conn:
    data = pd.read_sql(text("SELECT * FROM raw.extracted_geo_data"), conn)
data.head()

,_airbyte_raw_id,_airbyte_extracted_at,_airbyte_meta,_airbyte_generation_id,osm3s,version,elements,generator
0,01a0923c-2262-74c6-b57a-d605c45f0b5a,2026-09-11 20:49:58+00:00,"{'changes': [], 'sync_id': 9}",1,{'copyright': 'The data included in this docum...,0.6,"[{'id': 20714383, 'tags': {'name': 'W-X Row', ...",Overpass API 0.7.62.11 87bfad18

We have one line with all the json value. Let apply a transformation using DBT.

## Transformation with DBT

initialize the DBT project:

```
(base) C:\Users\sebas\Documents\geospatial_projects\pipeline_geospatial>dbt init pipeline_geospatial
21:10:19  Running with dbt=1.11.12
21:10:19
Your new dbt project "pipeline_geospatial" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

21:10:19  Setting up your profile.
Which database would you like to use?
[1] postgres

(Don't see the one you want? https://docs.getdbt.com/docs/available-adapters)

Enter a number: 1
host (hostname for the instance): 127.0.0.1
port [5432]: 5432
user (dev username): postgres
pass (dev password):
dbname (default database that dbt will build objects in): pipeline_geospatial
schema (default schema that dbt will build objects in): analytics
threads (1 or more) [1]: 4
21:12:16  Profile pipeline_geospatial written to C:\Users\sebas\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.

```
Check the connection with the Database:

```
(base) C:\Users\sebas\Documents\geospatial_projects\pipeline_geospatial\pipeline_geospatial>dbt debug
21:14:21  Running with dbt=1.11.12
21:14:21  dbt version: 1.11.12
21:14:21  python version: 3.12.13
21:14:21  python path: C:\Users\sebas\anaconda3\python.exe
21:14:21  os info: Windows-11-10.0.26200-SP0
21:14:21  Using profiles dir at C:\Users\sebas\.dbt
21:14:21  Using profiles.yml file at C:\Users\sebas\.dbt\profiles.yml
21:14:21  Using dbt_project.yml file at C:\Users\sebas\Documents\geospatial_projects\pipeline_geospatial\pipeline_geospatial\dbt_project.yml
21:14:21  adapter type: postgres
21:14:21  adapter version: 1.10.2
21:14:21  Configuration:
21:14:21    profiles.yml file [OK found and valid]
21:14:21    dbt_project.yml file [OK found and valid]
21:14:21  Required dependencies:
21:14:22   - git [OK found]

21:14:22  Connection:
21:14:22    host: 127.0.0.1
21:14:22    port: 5432
21:14:22    user: postgres
21:14:22    database: pipeline_geospatial
21:14:22    schema: analytics
21:14:22    connect_timeout: 10
21:14:22    role: None
21:14:22    search_path: None
21:14:22    keepalives_idle: 0
21:14:22    sslmode: None
21:14:22    sslcert: None
21:14:22    sslkey: None
21:14:22    sslrootcert: None
21:14:22    application_name: dbt
21:14:22    retries: 1
21:14:22  Registered adapter: postgres=1.10.2
21:14:22    Connection test: [OK connection ok]

21:14:22  All checks passed!
```

Create the  file `source.yml` to indicate to dbt the source, example:

```
version: 2

sources:
  - name: pipeline_geospatial
    description: database for geospatial data
    schema: raw
    tables:
      - name: extracted_geo_data
        description: retrieved OpenStreetMap data in a readable JSON format
``` 

Perform the transformation on the raw data using the following sql script which is in the staging model, example:

```
-- "C:\Users\sebas\Documents\geospatial_projects\pipeline_geospatial\pipeline_geospatial\models\staging\stg_extracted_geo_data.sql"
{{config(materialized='view')}}

SELECT 
    (data.value ->> 'id')::text AS osm_id,
    (data.value ->> 'type')::text AS osm_type,
    (data.value ->> 'bounds')::text AS osm_bounds,
    (data.value ->> 'geometry')::text AS osm_geometry,
    (data.value ->> 'nodes')::text AS nodes,
    (data.value ->> 'tags')::jsonb AS tags
FROM  {{source('pipeline_geospatial','extracted_geo_data')}} raw 
CROSS JOIN LATERAL jsonb_array_elements(raw.elements) AS data(value) -- jsonb_array_elements allows us to extract each element from the JSON array in the 'elements' column of the 'raw' table. Each element is treated as a separate row in the resulting view, enabling us to work with individual OpenStreetMap data entries.

```

Launch the following command:

```
(base) C:\Users\sebas\Documents\geospatial_projects\pipeline_geospatial\pipeline_geospatial>dbt run --select stg_extracted_geo_data
22:08:53  Running with dbt=1.11.12
22:08:53  Registered adapter: postgres=1.10.2
22:08:55  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.pipeline_geospatial.example
22:08:55  Found 1 model, 1 source, 476 macros
22:08:55
22:08:55  Concurrency: 4 threads (target='dev')
22:08:55
22:08:56  1 of 1 START sql view model analytics.stg_extracted_geo_data ................... [RUN]
22:08:56  1 of 1 OK created sql view model analytics.stg_extracted_geo_data .............. [CREATE VIEW in 0.28s]
22:08:56
22:08:56  Finished running 1 view model in 0 hours 0 minutes and 0.95 seconds (0.95s).
22:08:56
22:08:56  Completed successfully
22:08:56
22:08:56  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=1

```

Let check the created sql view in PostgreSQL.

In [9]:
with engine.connect() as conn:
    data_stg = pd.read_sql(text("SELECT * FROM analytics.stg_extracted_geo_data"), conn)
data_stg.head()

,osm_id,osm_type,osm_bounds,osm_geometry,nodes,tags
0,20714383,way,"{""maxlat"": 30.628834, ""maxlon"": -96.340566, ""m...","[{""lat"": 30.6277358, ""lon"": -96.340566}, {""lat...","[222454378, 4204990218, 222454386]","{'name': 'W-X Row', 'highway': 'service', 'pos..."
1,20718240,way,"{""maxlat"": 30.6301572, ""maxlon"": -96.3459838, ...","[{""lat"": 30.6301572, ""lon"": -96.3501748}, {""la...","[222493143, 222493147, 222493151, 3906238127, ...","{'name': 'Culpepper Drive', 'highway': 'reside..."
2,20721586,way,"{""maxlat"": 30.6288617, ""maxlon"": -96.3486331, ...","[{""lat"": 30.6288617, ""lon"": -96.3486331}, {""la...","[222493151, 222548389]","{'name': 'Fleetwood Street', 'highway': 'resid..."
3,20721589,way,"{""maxlat"": 30.6276251, ""maxlon"": -96.3486667, ...","[{""lat"": 30.6276251, ""lon"": -96.3486667}, {""la...","[222548400, 222548406]","{'name': 'Fleetwood Street', 'highway': 'resid..."
4,20721826,way,"{""maxlat"": 30.6303929, ""maxlon"": -96.3457865, ...","[{""lat"": 30.6270069, ""lon"": -96.3457865}, {""la...","[7903722112, 3906238131, 3906238140, 222552641]","{'hgv': 'yes', 'ref': 'TX 308', 'name': 'South..."